import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className="">
      <Layout title="Home Page" className="">
        <div>body</div>

        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
        <div>body</div>
      </Layout>
    </div>
  );
}
